config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'welcome#index'

  resources :users, only: [:index, :show, :new, :create] do
    resources :patches, only: [:new, :create, :show, :edit, :update]
    get 'user/:id/patches/delete', to: 'patches#destroy', as: 'destroy_patch'
  end

  get '/patches', to: 'patches#index'

  get '/login', to: 'sessions#new'

  get '/logout', to: 'sessions#destroy'

  resources :sessions, only: [:create]

  resources :categories, only: [:index, :show, :new, :create]

  get '/auth/twitter/callback' => 'sessions#create'

  resources :comments, only: [:show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :patchcategories
  has_many :patches, :through => :patchcategories

  validates :name, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :patch
end

app/models/patch.rb
class Patch < ApplicationRecord
  belongs_to :user
  has_many :patchcategories
  has_many :categories, :through => :patchcategories
  has_many :comments

  mount_uploader :file, FileUploader

  validates :name, presence: true

  accepts_nested_attributes_for :categories

  def self.newest_patches
    self.order('created_at desc')
  end

  def self.newest_patch
    self.newest_patches.limit(1)[0]
  end
end

app/models/patchcategory.rb
class Patchcategory < ApplicationRecord
  belongs_to :patch
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  has_many :patches
  has_many :comments

  has_secure_password

  validates_confirmation_of :password
  validates :username, presence: true, length: { minimum: 4}
  validates :username, uniqueness: true
  validates :password, length: { in: 6..30 }

  def self.newest_users
    self.order('created_at desc')
  end

  def self.newest_user
    self.newest_users.limit(1)[0]
  end

  def self.three_or_more
    self.all.select do |u|
       u.patches.count >= 3
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all

    respond_to do |f|
      f.js {render :json => @categories}
      f.html {render 'index'}
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    redirect_to user_path(User.find(session[:user_id]))
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def show
    @comment = Comment.find(comment_params)
    render json: @comment
  end

  def create
    @patch = Patch.find(params['comment']['patch_id'])
    @user = User.find(params['comment']['user_id'])

    @comment = @patch.comments.build(comment_params)
    @comment.save
    @user.comments << @comment

    respond_to do |f|
      f.js { render :json => @comment }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user_id, :patch_id, :username)
  end
end

app/controllers/patches_controller.rb
class PatchesController < ApplicationController

  def index
    @patches = Patch.all

    respond_to do |f|
      f.js {render :json => @patches}
      f.html {render 'index'}
    end
  end

  def show
    @user = current_patch_user
    @patch = current_patch

    respond_to do |f|
      f.js {render :json => @patch}
      f.html {render 'show'}
    end
  end

  def new
    @user = current_patch_user
    @patch = Patch.new
  end

  def create
    @user = current_patch_user
    @patch = @user.patches.build(patch_params)
    if @patch.save
      if params[:patch][:category]['name'] != ''
        @category = Category.create(name: params[:patch][:category]['name'])
        @category.patches << @patch
      end
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
    @user = current_patch_user
    @patch = current_patch
  end

  def update
    @user = current_patch_user
    @patch = current_patch

    if @patch.update(patch_params)
      if params[:patch][:category]['name'] != ''
        @category = Category.create(name: params[:patch][:category]['name'])
        @category.patches << @patch
      end

      redirect_to user_patch_path(@user, @patch)
    else
      render :edit
    end
  end

  def destroy
    user = current_patch_user
    patch = current_patch
    patch.destroy
    redirect_to user_path(user)
  end

  private

  def current_patch_user
    User.find(params[:user_id])
  end

  def current_patch
    Patch.find(params[:id])
  end

  def patch_params
    params.require(:patch).permit(:file, :name, :description, :game, :original, :category['name'], :category_ids => [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    if auth
      @user = User.find_or_create_by(uid: auth['uid']) do |u|
        u.username = auth['info']['name']
        u.password = SecureRandom.hex(4)
      end
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      @user = User.find_by(username: params[:session][:username])
      if @user && @user.authenticate(params[:session][:password])
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        flash[:notice] = 'Oh No!  Login Errors.'
        render :new
      end
    end
  end

  def destroy
    session.delete("user_id")
    redirect_to root_path
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])

    respond_to do |f|
      f.js {render :json => @user}
      f.html {render 'show'}
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def threeormore
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @patches = Patch.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/patches_helper.rb
module PatchesHelper
  def current_patch_user
    User.find(params[:user_id])
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def logged_in?
    session[:user_id]
  end

  def current_user
    if !session[:user_id]
      return nil
    else
      User.find(session[:user_id])
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/index.html.erb
<div class='row'>
  <div class='col-xl-12'>
  <h2>CATEGORIES:</h2>

    <ul id="categoryList"></ul>
  </div>
</div>

<script>
$("#categoryList").empty()

$(document).ready(function(){
  let CATEGORIES = []

  class Category {
    constructor(name, id) {
      this.name = name
      this.id = id

      CATEGORIES.push(this)
    }

    createLi() {
      return `<li class="categoryName">${this.name}</li>`
    }
  }

  $.ajax({
  type: "GET",
  url: window.location.pathname,
  dataType: "json"
  }).done(function(resp){
    $("#categoryList").empty()

    resp.forEach(function(v){
      new Category(v.name, v.id)
    })

    CATEGORIES.sort(function(a,b){
      return a.name.toUpperCase() > b.name.toUpperCase()
    })

    for(let v of CATEGORIES){
      $("#categoryList").append(v.createLi())
    }
  })
})
</script>

app/views/categories/new.html.erb
<div class='row'>
  <div class='col-lg-12'>
    <%= form_for @category do |f| %>
      Enter a new Category:<br /><br />
      <%= f.text_field :name %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<div class='row'>
  <div class='col-lg-12'>
    <h2><%= @category.name %></h2>

    <ul><% @category.patches.each do |p| %>
          <li><%= link_to p.name, user_patch_path(p.user, p) %> uploaded by <%= link_to p.user.username, user_path(p.user) %></li>
        <% end %></ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Patch Shair Dot COM</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
    <div class='row'>
      <div class='col-xl-12'>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
            <%= link_to 'View Patches', patches_path, class: "nav-item, nav-link" %>
            <%= link_to 'View Categories', categories_path, class: "nav-item, nav-link" %>
            <%= link_to 'User Profiles', users_path, class: "nav-item, nav-link" %>
            <%= link_to 'My Profile', user_path(User.find(session[:user_id])), class: "nav-item, nav-link" if logged_in? %>
            <%= link_to "Log Out", logout_path, class: "nav-item, nav-link" if logged_in? %>
          </div>
        </div>
      </nav>
    </div>

    <div class='col-sm-12'>
     <a href="/"><%= image_tag 'logo.png', class: 'img-fluid' %></a>
    </div>
    </div>
    <%= yield %>
    </div>
  </body>
</html>

app/views/patches/_errors.html.erb
<% if @patch.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@patch.errors.count, "error") %>
      prohibited this patch from being <%= message %>:
    </h2>

    <ul>
    <% @patch.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/patches/_form.html.erb
<%= form_for(patch, url: target_url) do |f| %>
  <div class="form-group">
    <!-- <label class="btn btn-dark"> -->
    <%= f.file_field :file, class: 'form-control-file', type: 'file'%>
    <!-- </label> -->
  </div>
  <div class="form-group">
    <%= f.text_field :name, :value => patch.name, class: 'form-control', placeholder: "Patch Name"%>
  </div>

  <div class="form-group">
    <%= f.text_field :description, class: 'form-control', placeholder: "Description" %>
  </div>

  <div class="form-group">
    <%= f.text_field :game, class: 'form-control', placeholder: "If from a game, which one?" %>
  </div>

  <div class="form-group">
    <%= f.fields_for( :category) do |c| %>
        <%= c.text_field :name, class: 'form-control', placeholder: "New Category?" %>
    <% end %>
  </div>

  <div class="form-group">
    Original?: &nbsp; <%= f.check_box :original %>
  </div>

  <div class="form-group">
    Category:   <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
                &nbsp;&nbsp;<%= b.label class:"label-checkbox" do%>
                  <%=b.check_box + ' ' + b.text%><% end %>
                <% end %>
  </div>


  <%= f.submit message, class: 'btn btn-dark'  %>
<% end %>

app/views/patches/_index.js.erb
<script>
    $("#patches").empty()
$(document).ready(function(){
  let PATCHES = []
  let pStart = 0
  let pEnd = 5

  class Patch {
    constructor(patchname, patch_id, username, user_id) {
      this.patchname = patchname
      this.patch_id = patch_id
      this.username = username
      this.user_id = user_id

      PATCHES.push(this)
    }

    createLi() {
      return `<li class="patch">
      <a href="/users/${this.user_id}/patches/${this.patch_id}">${this.patchname}</a><br>
      Posted By: <a href="/users/${this.user_id}">${this.username}</a></li>`
    }
  }

  $.ajax({
  type: "GET",
  url: window.location.pathname,
  dataType: "json"
  }).done(function(resp){
    resp.forEach(function(v){
      new Patch(v.name, v.id, v.user.username, v.user.id)
    })

    $("#patches").empty()

    for(let v of PATCHES.slice(pStart, pEnd)){
      $("#patches").append(v.createLi())
    }
  })

  $('#next').click(function(){
    $('#patches').empty()

    if (pEnd < PATCHES.length){
      pStart = pStart + 5
      pEnd = pEnd + 5
    }

    for(let v of PATCHES.slice(pStart, pEnd)){
      $("#patches").append(v.createLi())
    }
  })

  $('#prev').click(function(){
    $('#patches').empty()

    if (pStart > 0){
      pStart = pStart - 5
      pEnd = pEnd - 5
    }

    for(let v of PATCHES.slice(pStart, pEnd)){
      $("#patches").append(v.createLi())
    }
  })
})
</script>

app/views/patches/_show.js.erb
<script>
  $(document).ready(function (){

    let COMMENTS = []

    class Comment {
      constructor(content, userid, patchid, username) {
        this.content = content
        this.userid = userid
        this.patchid = patchid
        this.username = username

        COMMENTS.push(this)
      }

      makeJson(){
        return { comment: {user_id: `${this.userid}`, patch_id: `${this.patchid}`, content: `${this.content}`, username: `${this.username}`} }
      }

      createDiv(content, username) {
        return `<div class="comment"><p>${content}</p><p>Posted By: ${username}</p>`
      }
    }



    $('#newComment').submit( function (e){
      e.preventDefault()

      let newComment = new Comment($('#comment_content').val(), this.attributes[1].value, this.attributes[2].value, this.attributes[3].value)
      let token = this[2].value
      let data = newComment.makeJson()

      $.ajax({
        type: "POST",
        url: '/comments',
        data: data,
        authenticity_token: token,
        dataType: "json"
        })
      .done(function(resp) {
        $('#comments').prepend( () => newComment.createDiv(resp.content, resp.username))
        $('input#comment_content')[0].value = ''
       })
     })


     $.ajax({
       type: "GET",
       url: window.location.pathname,
       dataType: "json"
      }).done(function(resp){
        $('#comments').empty()
        resp.comments.reverse()
       resp.comments.forEach(function(value, index){
           let comment = new Comment(value.content, value.patch_id, value.user_id, value.username)
           $('#comments').append(comment.createDiv(comment.content, comment.username))
       })
     })
  });
</script>

app/views/patches/edit.html.erb
<div class='row'>
  <div class='col-lg-12'>
    <%= render partial: "form", locals: {patch: @patch, user: @user, target_url: user_patch_path(@user, @patch), message: 'Edit Patch'} %>

    <%= render partial: "errors", locals: {message: 'edited'} %>
  </div>
</div>

app/views/patches/index.html.erb
<div class='row'>
  <div class='col-sm-12'>
    <h2>PATCHES:</h2>
    <br />
    <button id="prev" class="btn btn-dark">Prev</button>
    <button id="next" class="btn btn-dark">Next</button>
    <br /><br />

    <ul id="patches"></ul>
  </div>
</div>

<%= render partial: 'index.js'%>

app/views/patches/new.html.erb
<div class='row'>
  <div class='col-lg-12'>
    <%= render partial: "form", locals: {patch: @patch, user: @user, target_url: user_patches_path(@user, @patch), message: 'Submit Patch'} %>

    <%= render partial: "errors", locals: {message: 'saved'} %>
  </div>
</div>

app/views/patches/show.html.erb
<div class='row'>
  <div class='col-lg-12'>
    <h2><%= @patch.name %></h2>

    <p><% if @patch.game != '' %>
          <%= 'FROM THE GAME: ' + @patch.game %>
        <% end %></p>

    <p><% if @patch.original == true %>
          <%= "Original Patch By " %> <%= link_to @patch.user.username, user_path(@patch.user) %>
        <% end %></p>

    <p><% if @patch.description != '' %>
          <%= "Description: " + @patch.description %>
        <% end %></p>

    <p>CATEGORIES: <% @patch.categories.each do |p| %>
                      <%= p.name %>
                    <% end %></p>

    <p><%= link_to 'Download', @patch.file.url %></p>

    <p><% if current_user == @patch.user %>
          <%= link_to 'Edit', edit_user_patch_path(@patch.user, @patch) %>
        <% end %></p>

    <p><% if current_user == @patch.user %>
          <%= link_to 'Delete', user_destroy_patch_path(@patch.user, @patch) %>
        <% end %></p>

    <% if logged_in? %>
      <%= form_tag("#", method: 'post', id: "newComment", :"data-userid" => current_user.id, :"data-patchid" => @patch.id, :"username" => current_user.username) do %>
        <div class="form-group">
        <%= text_field_tag 'comment_content', nil, class: 'form-control', placeholder: 'Comment Here' %>
        </div>
        <div class="form-group">
        <%= submit_tag "Post", :"data-disable-with" => false, class: 'btn btn-dark' %>
        </div>
      <% end %>
    <% end %>

    <div id="comments"></div>

     <%= render partial: 'show.js'%>
  </div>
 </div>

app/views/users/index.html.erb
<div class='row'>
  <div class='col-lg-12'>
    <h2>USERS:</h2>

    <ul><% @users.newest_users.each do |u| %>
      <li><%= link_to u.username, user_path(u) %></li>
    <% end %></ul>
  </div>
</div>

app/views/users/new.html.erb
<div class='row'>
  <div class='col-lg-12'>
    <%= form_for @user do |f| %>
      <div class="form-group">
        <label for="username">Username:</label>
        <%= f.text_field :username, class: 'form-control', type: 'username' %>
      </div>
      <div class="form-group">
        <label for="password">Password:</label>
        <%= f.password_field :password, class: 'form-control', type: 'password' %>
      </div>
      <div class="form-group">
        <label for="passwordConfirmation">Password Confirmation:</label>
        <%= f.password_field :password_confirmation, class: 'form-control', type: 'password' %>
      </div>
      <%= f.submit 'Create User', class: 'btn btn-dark'%>
    <% end %>

      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@user.errors.count, "error") %>
            prohibited this user from being saved:
          </h2>

          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class='row'>
  <div class='col-lg-12'>
    <h2><% if session[:user_id] == @user.id %>
          <%= 'you are logged in as: '%>
        <% end %> <%= @user.username %></h2>

    <h3><% if @user == current_user %>
      <%= link_to 'Upload a New Patch', new_user_patch_path(@user)  %>
      <% end %></h3>

    <h3><%= 'PATCHES:' if @user.patches.first != nil %></h3>

    <ul><% @user.patches.each do |p| %>
          <li><%= link_to p.name, user_patch_path(@user, p) %></li>
        <% end %></ul>
  </div>
</div>

app/views/welcome/index.html.erb
<div class='row'>

    <% if !logged_in? %>
      <div class='col-md-6'>
        <h3><%= link_to('Twitter Login / Sign Up', '/auth/twitter/') %></h3>
        <h3><%= link_to 'Log In', login_path %></h3>
        <h3><%= link_to 'Sign Up', new_user_path %></h3>
      </div>

      <div class='col-md-6'>
        <p>Create an account, upload music tracker patches, download other people's patches.</p>
        <p>Currently supports:</p>
        <ul>
            <li>DefleMask .y12 .dmp .bin</li>
            <li>Famitracker .fti</li>
        </ul>
      </div>
    <% end %>

    <% if logged_in? && !@patches.empty?%>
      <div class='col-sm-12'>
        <h2>NEWEST USER: <%= link_to User.newest_user.username, users_path(User.newest_user) %></h2>
        <h2>NEWEST PATCH: <%= link_to Patch.newest_patch.name, user_patch_path(Patch.newest_patch.user, Patch.newest_patch) %></h2>
      </div>
    <% end %>

</div>